version: '3'

services:
  db:
    image: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./../postgres_volume:/var/lib/postgresql/data
  web:
    build: .
    command: bash -c "./wait-for-it.sh db:5432 && ./docker-entrypoint.sh"
    #&& python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8000 "
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db

#&& python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8000